name: flutter_work_utils
description: Flutter Work utils for a faster work, the best utilities set
  together in a simple package
version: 0.2.5
homepage: https://github.com/Djcharles26/
repository: https://github.com/Djcharles26/flutter_work_utils.git

environment:
  sdk: ^3.6.0
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.18.0
  crypto: ^3.0.2
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter: null
